from mcp.server.fastmcp import FastMCP
from GoogleNews import GoogleNews
import google.generativeai as genai
import json
import os
import requests
from dotenv import load_dotenv

load_dotenv()

# Create MCP server
mcp = FastMCP("Google News Search")

genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
model = genai.GenerativeModel("gemini-2.0-flash")


@mcp.tool()
def search_news(
    keyword: str, language: str = "zh-TW", period: str = "2d", max_results: int = 4
) -> str:
    """
    First use Gemini API to generate 2 keywords related to the search term, then search Google News using these keywords, and compile the first max_results news articles with summaries.

    Args:
        keyword (str): Search keyword.
        language (str, optional): Language code, default is "zh-TW" (Traditional Chinese).
        period (str, optional): Time period, default is "2d" (news within 2 days).
        max_results (int, optional): Number of results to return, default is 4.

    Returns:
        str: JSON string of the first max_results news articles, including summaries generated by Gemini.
    """
    gemini_api_key = os.getenv("GEMINI_API_KEY")
    if not gemini_api_key:
        return json.dumps(
            {"error": "GEMINI_API_KEY environment variable not set"}, ensure_ascii=False, indent=2
        )
    GEMINI_API_URL = (
        "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key="
        + gemini_api_key
    )

    def get_related_keywords(keyword):
        headers = {"Content-Type": "application/json"}
        prompt = f"Please give me 2 Traditional Chinese keywords related to '{keyword}', return only a JSON array, no other explanations."
        data = {"contents": [{"parts": [{"text": prompt}]}]}
        try:
            resp = requests.post(GEMINI_API_URL, headers=headers, json=data, timeout=10)
            if resp.status_code == 200:
                import json as pyjson
                import re

                text = resp.json()["candidates"][0]["content"]["parts"][0]["text"]
                match = re.search(r"\[.*\]", text, re.DOTALL)
                if match:
                    return pyjson.loads(match.group(0))
                else:
                    return [keyword]
            else:
                return [keyword]
        except Exception:
            return [keyword]

    def get_insight(title, desc):
        try:
            prompt = f"Please provide an insight in Traditional Chinese (within 100 characters) for the news title: '{title}', and content snippet: '{desc}'"
            response = model.generate_content(prompt)
            print(
                "[Gemini Debug] response:",
                response.text.encode("cp950", errors="replace").decode("cp950"),
            )
            return response.text.strip()
        except Exception as e:
            return f"Insight error: {str(e)}"

    try:
        keywords = [keyword] + get_related_keywords(keyword)
        seen = set()
        all_news = []
        gn = GoogleNews(lang=language, period=period)
        for kw in keywords:
            gn.clear()
            gn.search(kw)
            for article in gn.results():
                unique_id = article.get("title", "") + article.get("link", "")
                if unique_id not in seen:
                    seen.add(unique_id)
                    all_news.append(article)
        # Take first max_results items
        formatted_results = []
        for article in all_news[:max_results]:
            title = article.get("title", "")
            desc = article.get("desc", "")
            insight = (
                get_insight(title, desc) if title and desc else "No title or content available for insight"
            )
            formatted_results.append(
                {
                    "title": title,
                    "link": article.get("link", "").split("?")[0],
                    "date": article.get("date", ""),
                    "description": desc,
                    "insight": insight,
                }
            )
        import json as pyjson

        return pyjson.dumps(formatted_results, ensure_ascii=False, indent=2)
    except Exception as e:
        return f"Error occurred during search: {str(e)}"

if __name__ == "__main__":
    print("Starting MCP server...")
    mcp.run()
